local fmt = require('solarized.fmt')
local p = require('solarized.palette')

return {
  gitDateHeader           = nil,
  gitIdentityHeader       = nil,
  gitIdentityKeyword      = nil,
  gitNotesHeader          = nil,
  gitReflogHeader         = nil,
  gitKeyword              = nil,
  gitIdentity             = nil,
  gitEmailDelimiter       = nil,
  gitEmail                = nil,
  gitDate                 = nil,
  gitMode                 = nil,
  gitHashAbbrev           = nil,
  gitHash                 = nil,
  gitReflogMiddle         = nil,
  gitReference            = nil,
  gitStage                = nil,
  gitType                 = nil,
  gitDiffAdded            = nil,
  gitDiffRemoved          = nil,
  gitcommitSummary        = nil,
  gitcommitComment        = { fmt('i'), p.fg('alt'), p.bg() },
  gitcommitUntracked      = { link = 'gitcommitComment' },
  gitcommitDiscarded      = { link = 'gitcommitComment' },
  gitcommitSelected       = { link = 'gitcommitComment' },
  gitcommitUnmerged       = { fmt('b'), p.fg('green'), p.bg() },
  gitcommitOnBranch       = { fmt('b'), p.fg('alt'), p.bg() },
  gitcommitBranch         = { fmt('b'), p.fg('magenta'), p.bg() },
  gitcommitNoBranch       = { link = 'gitcommitBranch' },
  gitcommitDiscardedType  = { fmt(), p.fg('red'), p.bg() },
  gitcommitSelectedType   = { fmt(), p.fg('green'), p.bg() },
  gitcommitUnmergedType   = nil,
  gitcommitType           = nil,
  gitcommitNoChanges      = nil,
  gitcommitHeader         = { fmt(), p.fg('alt'), p.bg() },
  gitcommitUntrackedFile  = { fmt('b'), p.fg('cyan'), p.bg() },
  gitcommitDiscardedFile  = { fmt('b'), p.fg('red'), p.bg() },
  gitcommitSelectedFile   = { fmt('b'), p.fg('green'), p.bg() },
  gitcommitUnmergedFile   = { fmt('b'), p.fg('yellow'), p.bg() },
  gitcommitFile           = { fmt('b'), p.fg('text'), p.bg() },
  gitcommitDiscardedArrow = { link = 'gitcommitDiscardedFile' },
  gitcommitSelectedArrow  = { link = 'gitcommitSelectedFile' },
  gitcommitUnmergedArrow  = { link = 'gitcommitUnmergedFile' },
  gitcommitArrow          = nil,
  gitcommitOverflow       = nil,
  gitcommitBlank          = nil,
}
